export const FETCH_POKEDEX_REQUEST = "FETCH_POKEDEX_REQUEST";
export const FETCH_POKEDEX_SUCCESS = "FETCH_POKEDEX_SUCCESS";
export const FETCH_POKEDEX_FAILURE = "FETCH_POKEDEX_FAILURE";
export const FETCH_POKEMON_DETAIL_SUCCESS = "FETCH_POKEMON_DETAIL_SUCCESS"
export const TO_NEXT_PAGE = "TO_NEXT_PAGE";
export const TO_PREV_PAGE = "TO_PREV_PAGE";
